export const GET_COLOR_START = "GET_COLOR_START";
export const GET_COLOR_SUCCESS = "GET_COLOR_SUCCESS";
export const GET_COLOR_FAILD = "GET_COLOR_FAILD";
export const FIND_BY_NAME_START_WITH_COLOR_START = "FIND_BY_NAME_START_WITH_COLOR_START";
export const FIND_BY_NAME_START_WITH_COLOR_SUCCESS = "FIND_BY_NAME_START_WITH_COLOR_SUCCESS";
export const FIND_BY_NAME_START_WITH_COLOR_FAILD = "FIND_BY_NAME_START_WITH_COLOR_FAILD";