export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const GET_PAGEABLE_PRODUCT_START = "GET_PAGEABLE_PRODUCT_START";
export const GET_PAGEABLE_PRODUCT_SUCCESS = "GET_PAGEABLE_PRODUCT_SUCCESS";
export const GET_PAGEABLE_PRODUCT_FAIL = "GET_PAGEABLE_PRODUCT_FAIL";

export const GET_FIND_ANY_PRODUCT_START = "GET_FIND_ANY_PRODUCT_START";
export const GET_FIND_ANY_PRODUCT_SUCCESS = "GET_FIND_ANY_PRODUCT_SUCCESS";
export const GET_FIND_ANY_PRODUCT_FAIL = "GET_FIND_ANY_PRODUCT_FAIL";

export const GET_ONE_PRODUCT_START = "GET_ONE_PRODUCT_START";
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS";
export const GET_ONE_PRODUCT_FAIL = "GET_ONE_PRODUCT_FAIL";