export const products = [
    {
        name: "FORUM MID SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/be90a4bada02409c8c59ac2801211eb2_9366/Donovan_Mitchell_D.O.N._Issue_2_Shoes_Orange_FX7425_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    },
    {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/2b3dd0565a074ed8a860ac840137a18c_9366/Ultraboost_21_Shoes_Grey_FY0372_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    },
    {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/02dc4bc845034b0aa997ac7c00b335aa_9366/ZX_2K_Boost_Pure_Shoes_Black_H06569_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/4811a18977b545b68e9dac7500f45896_9366/ZX_1K_Boost_Shoes_White_H69037_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/4811a18977b545b68e9dac7500f45896_9366/ZX_1K_Boost_Shoes_White_H69037_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/4811a18977b545b68e9dac7500f45896_9366/ZX_1K_Boost_Shoes_White_H69037_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/be90a4bada02409c8c59ac2801211eb2_9366/Donovan_Mitchell_D.O.N._Issue_2_Shoes_Orange_FX7425_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/4811a18977b545b68e9dac7500f45896_9366/ZX_1K_Boost_Shoes_White_H69037_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/be90a4bada02409c8c59ac2801211eb2_9366/Donovan_Mitchell_D.O.N._Issue_2_Shoes_Orange_FX7425_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/707bd9b6c1a44ce7bb58ac77012fcb2e_9366/Ultraboost_21_Shoes_Grey_FY0375_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    }, {
        name: "ZX 2K BOOST PURE SHOES",
        categories: ["Originals"],
        price: 150,
        discount:
            "This product is excluded from all promotional discounts and offers.",
        url:
            "https://assets.adidas.com/images/w_276,h_276,f_auto,q_auto:sensitive,fl_lossy/9357081632b842d5b5e1ac8c0104afcc_9366/Ultraboost_1.0_DNA_Shoes_Yellow_FX7977_01_standard.jpg",
        reviews: [],
        colors: ["Core Black", "Grey Six", "Orange"],
        sizes: [
            "7.5",
            "8",
            "8.5",
            "9",
            "9.5",
            "10",
            "10.5",
            "11",
            "11.5",
            "12",
            "13",
        ],
        specifications: [
            "Lace closure",
            "Textile upper",
            " Textile lining",
            " Boost midsole",
            " Rubber outsole",
            " Imported",
        ],
    },
];
